---
language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm -f ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
rvm:
- 2.2.3
gemfile:
- gemfiles/rails_3.2.gemfile
matrix:
  include:
  - rvm: 2.1.10
    gemfile: gemfiles/rails_3.2.gemfile
  fast_finish: true
